# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2288346865687a9d01a1014722efabae3a5fb13cb91d890cabfe7dc4c2a2a54ce74d6d2a7052e91dc1cbb9d815e7a28057fb444a19e0d0f5b7a12c7d7a505ca

test:
  secret_key_base: e624412a3662d4a6a6f2bc586ec5b73b41f12ab2836e46f1f916b8da10dde178cbfdb149fcf193f340a315ad4f17e30de70678357fcfed1fc394d052173645e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
