# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a63c5cd2d9d18f41a2550a592216bdf1324382ba493d53daf8d2aa9890d46e22a75b787604a7b25149af40c5a286df577826fe788f42ba5ed70109b33497df0

test:
  secret_key_base: 92775d8b93f8a28a07e0a47df53d1978f30660a6ac73c3af05bb1989ef1f53274ddea55c6376d7ab8d6df29a9437ae89aed51753a512d0810ace9ae59a998a2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
